---
- name: install mysql server
  apt:
    name={{ item }}
    update_cache={{ update_apt_cache }}
    state=installed
  with_items:
    - mysql-server-5.6
    - libmysqlclient-dev
    - python-dev
  tags: packages


- name: Ensure MySQL is running
  service:
    name=mysql
    state=started
    enabled=yes

- name: Install mysql connector for ansible
  pip:
    name=MySQL-python
    state=present

- name: update mysql root password for all root accounts
  mysql_user: 
    name=root
    password={{ mysql_root_password }}
    check_implicit_admin=true

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf 

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent

- name: Ensure database is created
  mysql_db:
    name={{ db_name }}
    encoding=utf8
    state=present

- name: Ensure user has access to database
  mysql_user:
    name={{ db_user }}
    password={{ db_password }}
    priv={{ db_name }}.*:ALL
    state=present
